# Generated by Django 4.0 on 2021-12-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wb_base',
            fields=[
                ('item_id', models.BigIntegerField(blank=None, primary_key=True, serialize=False, unique=True)),
                ('brand_name', models.CharField(max_length=250)),
                ('goods_name', models.CharField(max_length=250)),
                ('img', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('price_now', models.IntegerField(blank=None)),
                ('price_prev', models.IntegerField(blank=None)),
                ('price_min', models.IntegerField(blank=None)),
                ('price_max', models.IntegerField(blank=None)),
                ('b_count', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('company_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
