# Generated by Django 4.0 on 2021-12-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(blank=None, unique=True, verbose_name='ИД товара')),
                ('brand_name', models.CharField(max_length=250, verbose_name='Бренд')),
                ('goods_name', models.CharField(max_length=250, verbose_name='Производитель')),
                ('img', models.CharField(max_length=250, verbose_name='Фото')),
                ('price_now', models.IntegerField(blank=None)),
                ('price_min', models.IntegerField(blank=None)),
                ('price_max', models.IntegerField(blank=None)),
                ('timer', models.BigIntegerField(default=0)),
                ('b_count', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('flag', models.BooleanField()),
            ],
        ),
    ]
