# Generated by Django 4.0 on 2022-01-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='Тема')),
                ('message', models.TextField(max_length=1000, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
        migrations.CreateModel(
            name='wb_base',
            fields=[
                ('item_id', models.BigIntegerField(blank=None, primary_key=True, serialize=False, unique=True)),
                ('brand_name', models.CharField(max_length=250)),
                ('goods_name', models.CharField(max_length=250)),
                ('img', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('price_now', models.IntegerField(blank=None)),
                ('price_prev', models.IntegerField(blank=None)),
                ('price_min', models.IntegerField(blank=None)),
                ('price_max', models.IntegerField(blank=None)),
                ('b_count', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('company_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('product_type_name', models.CharField(max_length=50)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_time'],
            },
        ),
    ]
